# Site settings
title: "TonyGao的个人博客与记录"
author: "TonyGao"
description: "本博客以技术文章为主，另外记录博主的一些生活:)"
keywords: "网站开发, Web, PHP, Javascript, Symfony"
biography: "本人专业从事网站和网站系统开发，主要精力集中在PHP开发，前端开发和设计工作，<a href='https://github.com/TonyGao'>我的Github</a>"
colophon: "© 2018 by Tony Gao.<br>博客内容协议 <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> <br>本站基于 <a href='https://pages.github.com/'>Github Pages</a> 使用 <a href='http://jekyllrb.com/'>Jekyll</a> 创建。"

baseurl: ""
url: "https://tonygao.github.io/"

twitter_username: 
github_username: 
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
